blank_issues_enabled: false
contact_links:
  - name: Questions / general discussion
    url: [https://github.com/aleos-dev/singularity-project]
    about: Use Discussions for questions or open-ended ideas, not issues.
